fixtures:
  symlinks:
    ssl: "#{source_dir}"
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.0.2"
    # for omd/monitoring related tests
    omd:
      repo: "git://github.com/fnerdwq/puppet-omd"
    staging:
      repo: "git://github.com/nanliu/puppet-staging"
      ref: "1.0.0"
    xinetd:
      repo: "git://github.com/puppetlabs/puppetlabs-xinetd"
      ref: "1.3.1"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat"
      ref: "1.1.1"
