infrastructure::ec2::consul::ip: '10.10.10.17'
infrastructure::ec2::activemq::ip: '10.10.10.18'
infrastructure::ec2::elkstack::ip: '10.10.10.19'
infrastructure::ec2::rabbitmq::ip: '10.10.10.20'
infrastructure::ec2::sensu::ip: '10.10.10.21'
