
repo::path: '/vagrant/local_repo'

infrastructure::ec2::consul::ip: '10.10.10.17'
infrastructure::ec2::activemq::ip: '10.10.10.18'
infrastructure::ec2::elkstack::ip: '10.10.10.19'
infrastructure::ec2::rabbitmq::ip: '10.10.10.20'
infrastructure::ec2::sensu::ip: '10.10.10.21'
infrastructure::ec2::jenkins::ip: '10.10.10.22'
infrastructure::ec2::repo::ip: '10.10.10.23'
infrastructure::ec2::tomcat::ip: '10.10.10.24'

puppet::conf::environment: production