classes:
  - roles::db::barman

  
yum::repos:
  local_repo:
    descr: 'PaOsin.local repo - x86_64'
    baseurl: 'http://172.17.8.115/'
    
firewalld::ports:
  'Open port 5432 in the public zone':
    ensure: present
    zone: public
    port: 5432
    protocol: 'tcp'