classes:
  - roles::consul


sensu::checks:
  'check-consul-leader':
    command: '/opt/sensu/embedded/bin/check-consul-leader.rb'
  'check-service-servers':
    command: '/opt/sensu/embedded/bin/check-consul-servers.rb'
  'check-haproxy':
    command: '/opt/sensu/embedded/bin/check-haproxy.rb'   
  'checkpuppet-last-run':
    command: '/opt/sensu/embedded/bin/checkpuppet-last-run.rb'
    
    
consul::config_hash:
  log_level: 'INFO'
  server: true
  bootstrap_expect: 1
  ui_dir: '/opt/consul/ui'
  client_addr: '0.0.0.0'
  datacenter: 'paosin-md'
  domain: 'consul'
  data_dir:  '/opt/consul'
  bind_addr: "%{::ipaddress_eth1}"
  node_name: "%{::fqdn}"
  advertise_addr: "%{::ipaddress_eth1}"
  ca_file: "/apps/ssl/cacerts/intermediate.cert.pem"
  cert_file: "/apps/ssl/server_certs.pem"
  key_file: "/apps/ssl/key.pem"
  verify_incoming: false
  verify_outgoing: false
  ports:
    https: 8543
    

consul::services:
  'consul_server':
    port: 8500
    tags:
      - consul_server
    checks:
     - id: "%{::server_role}-healthcheck"
       name: "Healthcheck for service %{::server_role} in %{::environment}"
       service_id: "%{::environment}-%{::server_role}"
       tcp: "localhost:8500"
       interval: '10s'
       timeout: '1s'
