classes:
  - roles::ci::jenkins_master_server
  
jenkins::jenkins_ui_username: admin
jenkins::jenkins_ui_password: admin
  
consul::server: false 
consul::services:
  'tomcat-app':
    port: 8080
    token: "%{hiera('consul::service_write_token')}"
    tags:
      - tomcat_server
    checks:
     - id: "%{::server_role}-healthcheck"
       name: "Healthcheck for service %{::server_role} in %{::environment}"
       service_id: "%{::environment}-%{::server_role}"
       tcp: "localhost:8080"
       interval: '10s'
       timeout: '1s'
       
#firewall::ports:
# '101 allow Port 8140':
#   dport: [8080]
#   proto: 'tcp'
   
firewalld::ports:
  'Open port 8080 in the public zone':
    ensure: present
    zone: public
    port: 8080
    protocol: 'tcp'