classes:
  - roles::ci::jenkins_master_server
  
jenkins::jenkins_ui_username: admin
jenkins::jenkins_ui_password: admin

jenkins::plugins:
 git:
  version: '3.0.1'
 workflow-scm-step:
  version: '1.14.2'
 workflow-step-api:
  version: '1.14.2'
 git-client:
  version: '2.1.0'
 mailer:
  version: '1.18'
 matrix-project:
  version: '1.7.1'
 scm-api:
  version: '1.3'
 ssh-credentials:
  version: '1.12'
 token-macro:
  version: '1.12.1'
# display-url-api:
#  version: '0.2'
 junit:
  version: '1.3'
 script-security:
  version: '1.13'
 structs:
  version: '1.5'

consul::server: false 
consul::services:
  'jenkins':
    port: 8080
    token: "%{hiera('consul::service_write_token')}"
    tags:
      - jenkins_master_server
    checks:
     - id: "%{::server_role}-healthcheck"
       name: "Healthcheck for service %{::server_role} in %{::environment}"
       service_id: "%{::environment}-%{::server_role}"
       tcp: "localhost:8080"
       interval: '10s'
       timeout: '1s'
       
#firewall::ports:
# '101 allow Port 8140':
#   dport: [8080]
#   proto: 'tcp'



firewalld::ports:
  'Open port 8080 in the public zone':
    ensure: present
    zone: public
    port: 8080
    protocol: 'tcp'