classes:
  - roles::puppetmaster
  - epel

 

consul::server: false
consul::services:
  'puppet_server':
    port: 8140
    tags:
      - puppet_server
    checks:
     - id: "%{::server_role}-healthcheck"
       name: "Healthcheck for service %{::server_role} in %{::environment}"
       service_id: "%{::environment}-%{::server_role}"
       tcp: "localhost:8140"
       interval: '10s'
       timeout: '1s'


    


 
    